# =========================
# Build stage
# =========================
FROM node:18-alpine AS build

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install --omit=dev

# Copy source code
COPY server.js ./

# =========================
# Runtime stage
# =========================
FROM node:18-alpine

# OpenShift runs with random UID → group 0
WORKDIR /app
COPY --from=build /app /app

RUN chown -R 1001:0 /app \
 && chmod -R g=u /app

USER 1001

ENV NODE_ENV=production
EXPOSE 3000

CMD ["node", "server.js"]
