# -------- Build stage --------
FROM node:20-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm install --omit=dev
COPY server.js ./

# -------- Runtime stage (NO NPM) --------
FROM node:20-alpine

WORKDIR /app

# Remove npm completely
RUN rm -rf /usr/local/lib/node_modules/npm \
           /usr/local/bin/npm \
           /usr/local/bin/npx

COPY --from=build /app /app

RUN chown -R 1001:0 /app && chmod -R g=u /app
USER 1001

ENV NODE_ENV=production
EXPOSE 3000
CMD ["node", "server.js"]
