# =========================
# Frontend Dockerfile
# =========================
FROM nginxinc/nginx-unprivileged:1.26-alpine

USER root

RUN apk update && apk upgrade && \
    apk add --no-cache \
      libpng=1.6.53-r0 \
      libxml2=2.12.10-r0 && \
    rm -rf /var/cache/apk/*

RUN rm /etc/nginx/conf.d/default.conf \
 && mkdir -p /tmp \
 && chown -R 101:101 /tmp /var/cache/nginx /var/run

USER 101

COPY nginx.conf /etc/nginx/nginx.conf
COPY html/ /usr/share/nginx/html/

EXPOSE 8900
CMD ["nginx", "-g", "daemon off;"]
